# Generated by Django 4.2.10 on 2024-11-25 23:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favourite',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'url', 'name', 'status', 'last_location', 'first_seen', 'message')},
        ),
    ]
